add signature validation for ipnft metadata in the minting process
moleculeprotocol/IPNFT pull request #135
Opened 2023-07-05 08:06 UTC by nour-karoui

2023-07-05 08:27 UTC, elmariachi111 commented
please check why your formatter is reformatting everything and resubmit again. We're using forge as formatter (`forge fmt`). This should work out of the box.

2023-07-05 08:38 UTC, DorianWilhelm commented
@nour-karoui Do you mind fixing your local formatting settings? It's quite hard to find the actual changes :D

2023-07-05 11:59 UTC, elmariachi111 requested changes

2023-07-05 11:59 UTC, elmariachi111 commented on src/IPNFT.sol
> +    function mintReservation(
replace the other function with this one. There are no mintpasses after this change.

2023-07-05 11:59 UTC, elmariachi111 commented on src/Mintpass.sol
> +    function isValidSignature(bytes memory signature, string memory _tokenURI) external view override returns (bool) {
this function is fully unrelated to a mintpass. Instead, write a new Authorizer and adapt its interface to what you need. The existing one `function authorizeMint(address minter, address to, bytes memory data) external view returns (bool);` is totally sufficient to hand over signatures to the authorizer (you only must make sure to be able to reconstruct a signed message in the authorizer, but that can be virtually anything)

2023-07-10 08:05 UTC, elmariachi111 requested changes

2023-07-10 08:05 UTC, elmariachi111 commented on src/Mintpass.sol
> +import { ECDSA } from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
make sure this file doesn't change at all since it is not upgradeable.

2023-07-10 08:05 UTC, elmariachi111 commented on test/MintAuthorizer.t.sol
> +        bytes memory data =
don't use a fixed string. Create this signature inside the test.

2023-07-10 20:59 UTC, elmariachi111 approved these changes

2023-07-12 18:17 UTC, merged